[package]
name = "scallopy"
version = "0.1.8"
edition = "2018"

[lib]
name = "scallopy"
crate-type = ["cdylib"]

[dependencies]
scallop-core = { path = "../../core" }
sclc-core = { path = "../sclc" }
rayon = "1.5"

[dependencies.pyo3]
version = "0.16.5"
features = ["extension-module"]
