[package]
name = "scallopy"
version = "0.1.4"
edition = "2018"

[lib]
name = "scallopy"
crate-type = ["cdylib"]

[dependencies]
scallop-core = { path = "../../core" }
rayon = "1.5"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]
