[package]
name = "scallop-core"
version = "0.1.8"
authors = ["Ziyang Li <liby99@icloud.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[build-dependencies]
lalrpop = { version = "0.19.9", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.9"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
syn = "1.0"
paste = "1.0"
itertools = "0.10"
colored = "2.0"
petgraph = "0.6"
csv = "1.1"
sprs = "0.11"
chrono = "0.4"
dateparser = "0.1.6"
parse_duration = "2.1.1"
dyn-clone = "1.0.10"
lazy_static = "1.4"
rand = { version = "0.8", features = ["std_rng", "small_rng", "alloc"] }
sdd = { path = "../lib/sdd" }
