[package]
name = "scallop-core"
version = "0.1.3"
authors = ["Ziyang Li <liby99@icloud.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[build-dependencies]
lalrpop = { version = "0.19.0", features = ["lexer"] }

[dependencies]
lalrpop-util = "0.19.0"
proc-macro2 = { version = "1.0", features = ["span-locations"] }
quote = "1.0"
syn = "1.0"
paste = "1.0"
itertools = "0.10"
colored = "2.0"
petgraph = "0.6"
csv = "1.1"
sprs = "0.11"
rand = { version = "0.8", features = ["std_rng", "alloc"] }
sdd = { path = "../lib/sdd" }
